from html import escape
from io import BytesIO
from bs4 import BeautifulSoup
from app.db.legal_documents import get_document_by_id
from app.db.user_legal_acceptance import get_user_signed_document
from app.db.user_pool import get_user_by_userid
from app.utils.html_escape import escape_html as e
import re
from xhtml2pdf import pisa


def render_download_document(document_id: int, user_id: str):
    # --------------------------------
    # Verify user signed NDA
    # --------------------------------
    acceptance = get_user_signed_document(user_id, "nda")

    if not acceptance:
        return {
            "status": 403,
            "content_type": "text/plain",
            "file_bytes": b"You have not signed this document",
            "filename": "error.txt"
        }

    accepted_at = acceptance["accepted_at"]

    # --------------------------------
    # Fetch user
    # --------------------------------
    user = get_user_by_userid(user_id)

    if not user:
        return {
            "status": 404,
            "content_type": "text/plain",
            "file_bytes": b"User not found",
            "filename": "error.txt"
        }

    full_name = f"{user.get('FirstName','')} {user.get('LastName','')}".strip()

    # --------------------------------
    # Fetch document
    # --------------------------------
    document = get_document_by_id(document_id)

    if not document:
        return {
            "status": 404,
            "content_type": "text/plain",
            "file_bytes": b"Document not found",
            "filename": "error.txt"
        }

    title = e(document.get("title", "Legal Document"))
    version = e(str(document.get("version", "")))
    raw_content = document.get("content", "")

    # --------------------------------
    # Clean + sanitize HTML
    # --------------------------------
    soup = BeautifulSoup(raw_content, "html.parser")

    allowed_tags = {
        "p",
        "h1",
        "h2",
        "h3",
        "ul",
        "ol",
        "li",
        "strong",
        "em"
    }

    for tag in soup.find_all(True):
        if tag.name not in allowed_tags:
            tag.unwrap()
        tag.attrs = {}

    content = str(soup)

    # --------------------------------
    # Build PDF HTML
    # --------------------------------
    html = f"""
<html>
<head>
<meta charset="utf-8">
<title>{title}</title>
<style>
body {{
    font-family: Arial, Helvetica, sans-serif;
    max-width: 800px;
    margin: 40px auto;
    line-height: 1.6;
    font-size: 14px;
}}
h1 {{ text-align: center; margin-bottom: 20px; }}
h2 {{ margin-top: 25px; }}
.meta {{
    margin: 25px 0;
    padding: 15px;
    border: 1px solid #ccc;
    background: #f8f8f8;
}}
.meta div {{ margin-bottom: 6px; }}
.meta strong {{ display: inline-block; width: 140px; }}
hr {{ margin: 30px 0; }}
ul, ol {{ margin: 8px 0 8px 20px; padding-left: 0; }}
li {{ margin: 2px 0; line-height: 1.3; }}
.footer {{ margin-top: 60px; font-size: 12px; color: #666; }}
</style>
</head>

<body>

<h1>{title}</h1>

<div class="meta">
<div><strong>Version:</strong> {version}</div>
<div><strong>Agreed To By:</strong> {e(full_name)}</div>
<div><strong>User ID:</strong> {e(user_id)}</div>
<div><strong>Signed On:</strong> {e(str(accepted_at))}</div>
</div>

<hr>

<div class="legal-content">
{content}
</div>

<div class="footer">
Generated by the User Trial System
</div>

</body>
</html>
"""

    # --------------------------------
    # Convert HTML → PDF
    # --------------------------------
    pdf_buffer = BytesIO()

    pisa.CreatePDF(html, dest=pdf_buffer)

    pdf_bytes = pdf_buffer.getvalue()

    # --------------------------------
    # Safer filename
    # --------------------------------
    safe_title = re.sub(r'[^a-zA-Z0-9_\-]', '', title.replace(" ", "_"))

    return {
        "status": 200,
        "content_type": "application/pdf",
        "file_bytes": pdf_bytes,
        "filename": f"{safe_title}_signed.pdf"
    }